### ISSUE TITLE
Projects Database

### ISSUE THREAD

**Issue by kittyahy** [arnekuchenbecker/kitchen-planer-backend#20]

**Comment by kittyahy** [comment]
Do we also want to share shopping lists?

**Comment by arnekuchenbecker** [comment]
Yes. Shopping Lists in general should be shared, as well as what parts of them have already been bought (this might be a separate issue though). Unit conversion (matching both ingredient name and unit, where the name can also be a wildcard) should be stored per-project as well, to enable us to later add presets.
